export type BankQuestion = {
  id: string;
  tier: 1 | 2 | 3 | 4 | 5;
  category: string;
  source: string;
  question: string;
  answers: string[];
  correct: number;
  explanation: string;
};

export const extraQuestions: BankQuestion[] = [
  // NIVEL 1 — INTERMEDIO
  { id:"e01",tier:1,category:"Ética empresarial",source:"Programa de integridad",question:"Un superior pide modificar la fecha de un informe para ocultar un retraso. ¿Qué debe hacer el empleado?",answers:["Cambiarla por obediencia","Negarse y reportar por el canal adecuado","Cambiarla y guardar una copia","Esperar a la auditoría"],correct:1,explanation:"La presión jerárquica no justifica alterar registros; corresponde rechazar la instrucción y escalarla." },
  { id:"e02",tier:1,category:"Conflictos de interés",source:"Código de conducta",question:"¿Cuándo debe declararse un posible conflicto de interés?",answers:["Solo si produjo una pérdida","Antes de participar en la decisión relacionada","Después de firmar el contrato","Únicamente si lo solicita auditoría"],correct:1,explanation:"La declaración debe ser preventiva, de modo que el conflicto pueda gestionarse antes de influir en la decisión." },
  { id:"e03",tier:1,category:"Canales de denuncia",source:"Buenas prácticas de compliance",question:"¿Qué conducta constituye una represalia contra quien reportó de buena fe?",answers:["Confirmar la recepción","Cambiarle funciones como castigo","Proteger su identidad","Investigar de forma independiente"],correct:1,explanation:"Una medida laboral adversa motivada por la denuncia es una represalia, aunque se presente como reorganización." },
  { id:"e04",tier:1,category:"Conducta laboral",source:"Código de conducta",question:"Un comentario ofensivo se presenta como una broma habitual. ¿Cuál es la respuesta correcta?",answers:["Aceptarlo si no hubo intención","Evaluar su impacto y aplicar la política de respeto","Ignorarlo si ocurrió una vez","Publicarlo para obtener opiniones"],correct:1,explanation:"La ausencia alegada de intención no elimina el impacto ni la obligación de mantener un entorno respetuoso." },
  { id:"e05",tier:1,category:"Regalos",source:"Política de regalos",question:"¿Qué elemento hace especialmente riesgoso un regalo comercial?",answers:["Que tenga empaque","Que coincida con una decisión pendiente","Que se entregue en la oficina","Que incluya una tarjeta"],correct:1,explanation:"La proximidad a una decisión puede crear influencia indebida real o aparente." },
  { id:"e06",tier:1,category:"Protección de datos",source:"Principios de privacidad",question:"¿Qué debe ocurrir cuando termina la finalidad autorizada para conservar un dato personal?",answers:["Conservarlo indefinidamente","Eliminarlo o anonimizarlo según la política","Publicarlo","Transferirlo al proveedor"],correct:1,explanation:"La limitación de conservación exige no mantener datos personales más tiempo del necesario." },
  { id:"e07",tier:1,category:"Proveedores",source:"Gestión de terceros",question:"¿Por qué debe documentarse la selección de un proveedor?",answers:["Para aumentar correos","Para demostrar criterios objetivos y trazabilidad","Para evitar contratos","Para reemplazar la debida diligencia"],correct:1,explanation:"La documentación permite verificar que la decisión fue objetiva, autorizada y libre de influencias indebidas." },
  { id:"e08",tier:1,category:"Seguridad de la información",source:"Higiene digital",question:"Un empleado recibe un enlace urgente para restablecer su contraseña. ¿Cuál es la primera medida prudente?",answers:["Abrirlo desde el móvil","Verificar el remitente y acceder por el canal oficial","Reenviarlo al equipo","Responder con la contraseña actual"],correct:1,explanation:"La urgencia es una señal común de phishing; debe verificarse por canales confiables." },
  { id:"e09",tier:1,category:"Competencia justa",source:"Principios de libre competencia",question:"Un competidor propone acordar precios mínimos. ¿Qué debe hacer el empleado?",answers:["Escuchar sin tomar notas","Rechazar, retirarse y reportar","Aceptar si es verbal","Consultar a otros competidores"],correct:1,explanation:"Los acuerdos de precios entre competidores son una de las restricciones más graves a la competencia." },
  { id:"e10",tier:1,category:"Registros",source:"Controles internos",question:"¿Cuál es el propósito principal de conservar registros completos y exactos?",answers:["Evitar toda auditoría","Permitir trazabilidad y rendición de cuentas","Reducir autorizaciones","Ocultar información sensible"],correct:1,explanation:"Los registros íntegros permiten reconstruir decisiones, operaciones y responsabilidades." },

  // NIVEL 2 — AVANZADO
  { id:"a01",tier:2,category:"Debida diligencia",source:"Gestión de terceros",question:"¿Qué hallazgo amerita ampliar la revisión de un distribuidor?",answers:["Tiene página web","No puede explicar quiénes son sus propietarios","Entrega referencias","Usa contrato escrito"],correct:1,explanation:"La opacidad sobre propiedad y control impide evaluar beneficiarios finales y riesgos asociados." },
  { id:"a02",tier:2,category:"Antisoborno",source:"Controles anticorrupción",question:"Una donación es solicitada por un funcionario que decide un permiso. ¿Qué control es prioritario?",answers:["Cambiar la palabra donación","Analizar vínculo, finalidad y posible quid pro quo","Pagar en efectivo","Solicitar recibo después"],correct:1,explanation:"La conexión con una decisión oficial puede convertir la donación en un vehículo de influencia indebida." },
  { id:"a03",tier:2,category:"Protección de datos",source:"Privacidad desde el diseño",question:"¿Qué significa aplicar privacidad desde el diseño?",answers:["Añadir avisos al final","Integrar salvaguardas desde la concepción del proceso","Cifrar solo tras un incidente","Delegar toda responsabilidad al usuario"],correct:1,explanation:"La privacidad debe incorporarse desde el diseño y durante todo el ciclo de vida del tratamiento." },
  { id:"a04",tier:2,category:"Canales de denuncia",source:"Investigaciones internas",question:"Una denuncia involucra al responsable habitual de investigarla. ¿Qué medida preserva independencia?",answers:["Permitirle dirigir el caso","Asignar un investigador sin conflicto","Cerrar por falta de competencia","Compartirla con todo el equipo"],correct:1,explanation:"La investigación debe reasignarse para evitar que una persona investigue hechos que la comprometen." },
  { id:"a05",tier:2,category:"Acoso",source:"Conducta laboral",question:"¿Qué distingue mejor el acoso de una retroalimentación legítima?",answers:["Toda crítica es acoso","La humillación o conducta hostil, no la exigencia objetiva","El cargo de quien habla","Que exista correo electrónico"],correct:1,explanation:"Una evaluación exigente puede ser legítima; la intimidación, humillación o hostilidad no lo son." },
  { id:"a06",tier:2,category:"Seguridad de la información",source:"Gestión de incidentes",question:"Tras enviar datos sensibles al destinatario equivocado, ¿qué debe hacerse primero?",answers:["Borrar el correo enviado","Activar de inmediato el protocolo de incidentes","Esperar una queja","Pedir al destinatario que no diga nada"],correct:1,explanation:"La contención y evaluación tempranas permiten reducir el daño y cumplir eventuales deberes de notificación." },
  { id:"a07",tier:2,category:"Competencia",source:"Libre competencia",question:"En una asociación gremial se comparte información futura de precios. ¿Cuál es el riesgo principal?",answers:["Exceso de transparencia pública","Coordinación anticompetitiva","Duplicación contable","Violación de propiedad intelectual"],correct:1,explanation:"El intercambio de información estratégica futura puede facilitar coordinación entre competidores." },
  { id:"a08",tier:2,category:"Conflictos de interés",source:"Gobierno corporativo",question:"Un miembro del comité tiene una inversión pequeña en un oferente. ¿Qué análisis corresponde?",answers:["Ignorarla por ser pequeña","Evaluar materialidad, influencia y apariencia, y declararla","Venderla después de votar","Informarla solo al oferente"],correct:1,explanation:"La gestión considera tanto la influencia real como la apariencia razonable de parcialidad." },
  { id:"a09",tier:2,category:"Proveedores",source:"Debida diligencia continua",question:"¿Cuándo termina la debida diligencia de un tercero?",answers:["Al firmar el contrato","Debe continuar según riesgo durante la relación","Al recibir la primera factura","Cuando entrega certificaciones"],correct:1,explanation:"Los riesgos y las circunstancias cambian; el monitoreo debe mantenerse durante la relación." },
  { id:"a10",tier:2,category:"Regalos y hospitalidad",source:"Controles anticorrupción",question:"¿Qué combinación ofrece el control más sólido sobre hospitalidad?",answers:["Monto libre y aprobación posterior","Límites, finalidad legítima, aprobación y registro","Pago en efectivo y discreción","Decisión exclusiva del anfitrión"],correct:1,explanation:"La proporcionalidad debe complementarse con aprobación, transparencia y registro verificable." },

  // NIVEL 3 — ESPECIALISTA
  { id:"s01",tier:3,category:"LA/FT",source:"GAFI — Recomendación 10",question:"¿Qué debe verificarse respecto de una persona que actúa en nombre de un cliente?",answers:["Solo su correo","Su identidad y autorización para actuar","Únicamente su nacionalidad","Su historial académico"],correct:1,explanation:"La debida diligencia cubre la identidad de la persona y la legitimidad de su representación." },
  { id:"s02",tier:3,category:"PEP",source:"GAFI — Recomendación 12",question:"¿Por qué el estatus de PEP no implica por sí mismo actividad criminal?",answers:["Porque elimina todo riesgo","Porque es un factor de riesgo que exige medidas proporcionales","Porque solo aplica a bancos centrales","Porque sustituye la identificación"],correct:1,explanation:"Ser PEP no equivale a culpabilidad; activa un tratamiento reforzado basado en riesgo." },
  { id:"s03",tier:3,category:"Beneficiario final",source:"GAFI — Recomendación 24",question:"Si no se identifica control por propiedad, ¿qué debe examinarse después?",answers:["La marca comercial","El control por otros medios","El domicilio del contador","El banco corresponsal"],correct:1,explanation:"La metodología escalonada exige revisar otras formas de control antes de acudir al directivo superior." },
  { id:"s04",tier:3,category:"Operaciones sospechosas",source:"GAFI — Recomendación 20",question:"¿Qué umbral conceptual activa un reporte de operación sospechosa?",answers:["Una condena penal","Sospecha o motivos razonables para sospechar","Un monto mínimo universal","La autorización del cliente"],correct:1,explanation:"No se exige probar el delito ni existe un umbral monetario universal para la sospecha." },
  { id:"s05",tier:3,category:"Tipping-off",source:"GAFI — Recomendación 21",question:"¿Qué conducta puede constituir revelación indebida?",answers:["Conservar soportes","Informar al cliente que fue presentado un reporte sospechoso","Actualizar el perfil de riesgo","Atender una orden válida"],correct:1,explanation:"Revelar la existencia o preparación de un reporte puede frustrar investigaciones y está generalmente prohibido." },
  { id:"s06",tier:3,category:"Sanciones",source:"GAFI — Recomendación 6",question:"¿Qué caracteriza la congelación de activos bajo sanciones financieras dirigidas?",answers:["Requiere avisar previamente","Debe ejecutarse sin demora cuando corresponde","Transfiere la propiedad al banco","Solo aplica a efectivo"],correct:1,explanation:"La eficacia de la medida depende de impedir inmediatamente la disposición de fondos u otros activos." },
  { id:"s07",tier:3,category:"Activos virtuales",source:"GAFI — Recomendación 15",question:"¿Qué entidad queda normalmente comprendida como proveedor de servicios de activos virtuales?",answers:["Un usuario que paga una vez","Una empresa que intercambia activos virtuales por moneda fiduciaria","Un fabricante de computadores","Una universidad que estudia blockchain"],correct:1,explanation:"El intercambio profesional de activos virtuales y moneda fiduciaria es una actividad cubierta por el estándar." },
  { id:"s08",tier:3,category:"Banca corresponsal",source:"GAFI — Recomendación 13",question:"Antes de establecer una relación corresponsal transfronteriza, ¿qué debe evaluarse?",answers:["Solo la tarifa","Reputación, supervisión y controles ALA/CFT del corresponsal","El diseño de su tarjeta","Número de sucursales locales"],correct:1,explanation:"La entidad debe comprender el negocio y la calidad de supervisión y controles de la institución respondiente." },
  { id:"s09",tier:3,category:"Conservación de registros",source:"GAFI — Recomendación 11",question:"¿Para qué deben ser suficientes los registros de transacciones?",answers:["Para publicidad","Para reconstruir operaciones individuales","Para reemplazar al beneficiario final","Para eliminar alertas"],correct:1,explanation:"Los registros deben permitir reconstruir transacciones y servir como evidencia cuando sea necesario." },
  { id:"s10",tier:3,category:"Transferencias",source:"GAFI — Recomendación 16",question:"Una institución intermediaria detecta una transferencia sin datos exigidos. ¿Qué debe tener definido?",answers:["Una regla de aprobación automática","Políticas para ejecutar, rechazar o suspender según riesgo","Una tarifa adicional","Un mecanismo para borrar el mensaje"],correct:1,explanation:"Debe contar con procedimientos basados en riesgo para tratar transferencias con información incompleta." },

  // NIVEL 4 — EXPERTO
  { id:"x01",tier:4,category:"Enfoque basado en riesgo",source:"GAFI — Recomendación 1",question:"Una entidad aplica debida diligencia simplificada a un producto sin documentar riesgo bajo. ¿Cuál es la falla?",answers:["No cobró comisión","No sustentó la proporcionalidad de la medida","No usó biometría","No consultó al competidor"],correct:1,explanation:"Las medidas simplificadas deben apoyarse en una evaluación que demuestre menor riesgo y no existir sospecha." },
  { id:"x02",tier:4,category:"Congelación",source:"GAFI — Recomendaciones 6 y 7",question:"¿Qué diferencia conceptual existe entre congelar y decomisar activos?",answers:["Son idénticos","Congelar impide temporalmente disponer; decomisar priva mediante autoridad competente","Congelar transfiere propiedad","Decomisar requiere consentimiento"],correct:1,explanation:"La congelación restringe disposición sin alterar necesariamente la propiedad; el decomiso produce privación definitiva." },
  { id:"x03",tier:4,category:"UIF",source:"GAFI — Recomendación 29",question:"¿Cuál es la función central de una unidad de inteligencia financiera?",answers:["Condenar delitos","Recibir, analizar y diseminar información financiera relevante","Auditar estados financieros","Autorizar todos los pagos"],correct:1,explanation:"La UIF actúa como centro nacional para transformar reportes en inteligencia financiera y diseminarla." },
  { id:"x04",tier:4,category:"Supervisión",source:"GAFI — Recomendación 26",question:"¿Qué implica una supervisión ALA/CFT basada en riesgo?",answers:["Revisar a todos igual","Ajustar frecuencia e intensidad al perfil de riesgo","Inspeccionar solo tras condenas","Delegar todo al sujeto obligado"],correct:1,explanation:"Los recursos de supervisión deben concentrarse proporcionalmente en riesgos mayores." },
  { id:"x05",tier:4,category:"Investigación interna",source:"Buenas prácticas internacionales",question:"Una investigación encuentra indicios creíbles contra un alto directivo. ¿Qué protege mejor su integridad?",answers:["Permitirle seleccionar investigadores","Preservar evidencia, independencia y escalamiento al órgano competente","Esperar rumores externos","Destruir borradores"],correct:1,explanation:"La cadena de custodia, independencia y gobierno del caso son esenciales, especialmente frente a alta dirección." },
  { id:"x06",tier:4,category:"Riesgo de terceros",source:"OCDE — Controles internos",question:"Una empresa terceriza ventas pero no puede revisar los libros del agente. ¿Qué debilidad surge?",answers:["Exceso de independencia","Falta de derechos de auditoría y monitoreo","Duplicidad de marca","Riesgo cambiario únicamente"],correct:1,explanation:"Sin derechos contractuales y monitoreo, la empresa pierde capacidad para detectar pagos y conductas impropias." },
  { id:"x07",tier:4,category:"Proliferación",source:"GAFI — Recomendación 7",question:"¿Qué objetivo tienen las sanciones financieras dirigidas relativas a proliferación?",answers:["Regular precios de armas","Implementar resoluciones del Consejo de Seguridad sobre financiación de proliferación","Sancionar toda exportación","Sustituir controles aduaneros"],correct:1,explanation:"La Recomendación 7 vincula la congelación y prohibición de fondos con resoluciones aplicables del Consejo de Seguridad." },
  { id:"x08",tier:4,category:"Transparencia societaria",source:"GAFI — Recomendaciones 24 y 25",question:"¿Qué cualidad debe tener la información de beneficiario final disponible a autoridades?",answers:["Ser solo declarativa","Ser adecuada, exacta y actualizada","Estar limitada a accionistas nominales","Ser opcional para estructuras jurídicas"],correct:1,explanation:"La utilidad operativa depende de información adecuada, exacta y actualizada accesible oportunamente." },
  { id:"x09",tier:4,category:"Secreto profesional",source:"GAFI — Recomendación 9",question:"¿Qué exige el estándar respecto de leyes de secreto financiero?",answers:["Su eliminación total","Que no inhiban la implementación de las Recomendaciones","Que prevalezcan ante toda solicitud","Que solo protejan pagos internacionales"],correct:1,explanation:"La confidencialidad legítima no debe impedir el acceso e intercambio de información requerido por el sistema preventivo." },
  { id:"x10",tier:4,category:"Evaluación mutua",source:"Metodología GAFI",question:"¿Qué diferencia existe entre cumplimiento técnico y efectividad?",answers:["No existe diferencia","El primero revisa el marco; la segunda, los resultados alcanzados","La efectividad solo cuenta leyes","El técnico solo mide condenas"],correct:1,explanation:"La evaluación técnica examina requisitos normativos e institucionales; la efectividad analiza resultados inmediatos." },

  // NIVEL 5 — EXPERTO INTERNACIONAL
  { id:"i01",tier:5,category:"ONU",source:"Convención de las Naciones Unidas contra la Corrupción",question:"¿Qué área distingue especialmente a la Convención de la ONU contra la Corrupción como instrumento integral?",answers:["Fijación de tasas de interés","Prevención, criminalización, cooperación y recuperación de activos","Regulación de marcas","Arbitraje deportivo"],correct:1,explanation:"La Convención articula medidas preventivas, delitos, cooperación internacional y recuperación de activos." },
  { id:"i02",tier:5,category:"OCDE",source:"Convención Anticohecho",question:"¿En qué lado de la transacción se concentra especialmente la Convención Anticohecho de la OCDE?",answers:["En la demanda del consumidor","En la oferta de sobornos a funcionarios públicos extranjeros","En donaciones entre particulares","En conflictos laborales"],correct:1,explanation:"El instrumento se enfoca en criminalizar el soborno activo de funcionarios públicos extranjeros en negocios internacionales." },
  { id:"i03",tier:5,category:"ONU",source:"Resolución 1373 (2001)",question:"¿Qué obligación central introdujo la Resolución 1373 frente a la financiación del terrorismo?",answers:["Crear una moneda común","Prevenir y reprimir la financiación y congelar activos vinculados","Eliminar fronteras","Privatizar las UIF"],correct:1,explanation:"La resolución exige medidas nacionales contra financiación terrorista, incluida la congelación de fondos vinculados." },
  { id:"i04",tier:5,category:"ONU",source:"Resolución 2462 (2019)",question:"¿Qué caracteriza a la Resolución 2462 del Consejo de Seguridad?",answers:["Regula comercio marítimo","Es la primera resolución dedicada específicamente a prevenir y reprimir financiación del terrorismo","Crea el GAFI","Elimina evaluaciones de riesgo"],correct:1,explanation:"La Resolución 2462 consolidó un marco específico y amplio sobre financiación del terrorismo." },
  { id:"i05",tier:5,category:"OCDE",source:"Conducta empresarial responsable",question:"En la debida diligencia de la OCDE, ¿qué sigue a identificar y evaluar impactos adversos?",answers:["Ocultarlos","Detenerlos, prevenirlos o mitigarlos","Transferirlos al Estado","Cerrar automáticamente toda operación"],correct:1,explanation:"La debida diligencia exige actuar sobre los impactos identificados de forma proporcional y verificable." },
  { id:"i06",tier:5,category:"Basilea",source:"Comité de Supervisión Bancaria de Basilea",question:"¿Qué condición fortalece la independencia de la función de cumplimiento bancaria?",answers:["Que sea responsable de ventas","Acceso al órgano de gobierno y recursos adecuados","Que no pueda investigar","Remuneración ligada solo a ingresos"],correct:1,explanation:"La función requiere autoridad, recursos, independencia y líneas de reporte que permitan escalar fallas materiales." },
  { id:"i07",tier:5,category:"Cooperación",source:"GAFI — Recomendación 40",question:"¿Qué salvaguarda debe acompañar el intercambio internacional de información?",answers:["Publicación automática","Uso autorizado, confidencialidad y protección de la información","Eliminación de registros","Consentimiento del investigado"],correct:1,explanation:"La cooperación eficaz debe coexistir con controles sobre finalidad, seguridad y confidencialidad." },
  { id:"i08",tier:5,category:"Extradición",source:"GAFI — Recomendación 39",question:"¿Cómo trata el estándar los delitos de lavado y financiación del terrorismo respecto de extradición?",answers:["Como faltas administrativas","Como delitos extraditables con cooperación eficaz","Como asuntos exclusivamente privados","Como excepciones al auxilio judicial"],correct:1,explanation:"Los países deben permitir extradición efectiva o, cuando corresponda, procesar internamente a sus nacionales." },
  { id:"i09",tier:5,category:"Recuperación de activos",source:"UNCAC / GAFI",question:"¿Por qué la cooperación internacional es esencial para recuperar activos?",answers:["Porque los activos siempre son efectivo","Porque estructuras, evidencia y bienes suelen atravesar jurisdicciones","Porque elimina el debido proceso","Porque sustituye las sentencias"],correct:1,explanation:"Los flujos ilícitos explotan fronteras; localizar, congelar, decomisar y restituir requiere coordinación entre autoridades." },
  { id:"i10",tier:5,category:"Caso internacional",source:"GAFI · ONU · OCDE",question:"Una filial usa un consultor para pagar a una sociedad opaca ligada a un funcionario extranjero. ¿Qué marco integrado resulta más pertinente?",answers:["Solo protección de datos","Antisoborno, beneficiario final, debida diligencia y reporte de sospecha","Únicamente derecho laboral","Solo política de regalos"],correct:1,explanation:"El caso combina corrupción transnacional, opacidad societaria, riesgo de terceros y posibles flujos ilícitos." },
];
